export enum AppActionTypes {
  TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE',
  CHANGE_TEMP_UNIT = 'CHANGE_TEMP_UNIT',
  SET_IS_LOADING = 'SET_IS_LOADING',
  SET_IS_ERROR = 'SET_IS_ERROR',
  SET_IS_INITIAL = 'SET_IS_INITIAL',
}

export enum WeatherActionTypes {
  FETCH_WEATHER_START = 'FETCH_WEATHER_START',
  FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS',
  FETCH_WEATHER_FINISH = 'FETCH_WEATHER_FINISH',
  FETCH_WEATHER_ERROR = 'FETCH_WEATHER_ERROR',
}
